---
language: python
python: "3.6"

sudo: required

services:
  - docker

addons:
  apt:
    packages:
    - python-pip

install:
  - pip install ansible

before_script:
  - docker run --name xenial -d codeyourinfra/python3:xenial
  - docker run --name bionic -d codeyourinfra/python3:bionic

script:
  - ansible-galaxy install -r requirements.yml -p tests/roles
  - ansible-playbook tests/test.yml -i tests/inventory

after_script:
  - docker stop xenial bionic
  - docker rm xenial bionic

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: GXsq6LjPE/ioNeIjCmPrHkgFvlW4q1KmcqtL5A3dz3QIwes8m1Mf341iqwYRj+HrjUwU/XHYB6ksINqfk0PpQREByn9G4Lu3VQawkT2T+vVjW8bcT1lHHVjZUrswDjcoaa2oXBZPJTfYMC2fMrONe+SjH6HIIRxsZEwyVRBFCOHhtyaxryiv3ijGapcPCsZ/jcXvZPmfijmCj2Qjd4mjrZs/B2eACAquwN6ixqeQ6BLn/uIKfN3TDeuCsRp7UMRvAQ8iXPnWKjoFbiUK22esd7s228Pdb+0XYB3Ae7jPJTf995izoHUxc1EVPlGHiOc8jfRSKnLax+9Z5KJLj9RBM01/G5Ac4wp92dWaqyWBs+ea/53rizqZe4QBB/ov3mttsbtE18Q3LMGAHzwkA6Bdp0C3wbJP4sdcoN5z0/KbDM4U6u4NB6uFtWqa58thlNi/tIicZ/2VQ0SFOAizUa8aEBiEKv4s6nizsuFpS/hPxdEHpoPQmGRG+KzWgnY1E+Fd4FJ25gXjb7CP8TcXrg1bIJTlueiYN11QTyH4ghocbUCo7n0l5ZOvfOgoGI3Hi9mS+7tklBXgYboiMCnnaT4WassciyxZkcPrAwu+zPlAhdnruls3sJRYYelB2z1x+UyAyN9CAXs68QHQlPsbGASblAKqVFrQCR3KTU2mdVsTHRE=
